/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HonoraryRouteImport } from './routes/honorary'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersSlugRouteImport } from './routes/players.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HonoraryRoute = HonoraryRouteImport.update({
  id: '/honorary',
  path: '/honorary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersSlugRoute = PlayersSlugRouteImport.update({
  id: '/players/$slug',
  path: '/players/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/honorary': typeof HonoraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/players/$slug': typeof PlayersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/honorary': typeof HonoraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/players/$slug': typeof PlayersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/honorary': typeof HonoraryRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/players/$slug': typeof PlayersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/honorary' | '/sitemap.xml' | '/players/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/honorary' | '/sitemap.xml' | '/players/$slug'
  id: '__root__' | '/' | '/honorary' | '/sitemap.xml' | '/players/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HonoraryRoute: typeof HonoraryRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PlayersSlugRoute: typeof PlayersSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/honorary': {
      id: '/honorary'
      path: '/honorary'
      fullPath: '/honorary'
      preLoaderRoute: typeof HonoraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$slug': {
      id: '/players/$slug'
      path: '/players/$slug'
      fullPath: '/players/$slug'
      preLoaderRoute: typeof PlayersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HonoraryRoute: HonoraryRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PlayersSlugRoute: PlayersSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
